language: python
python:
    - 3.4
    - 3.3
    - 2.7
sudo: false
env:
install:
    - pip install . coveralls
script:
    - nosetests --with-coverage --cover-package=nbformat nbformat
after_success:
    - coveralls
