language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
env:
install:
    - pip install . codecov
    - pip install nbformat[test]
script:
    - nosetests --with-coverage --cover-package=nbformat nbformat
after_success:
    - codecov
