language: python
dist: xenial
python:
    - nightly
    - 3.8
    - 3.7
    - 3.6
    - 3.5
sudo: false
install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade pytest
    - pip install . codecov
    - pip install nbformat[test]
    - pip freeze
script:
    - py.test -v --cov nbformat nbformat
after_success:
    - codecov
matrix:
  allow_failures:
    - python: "nightly"
