language: python
python:
    - nightly
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
env:
install:
    - pip install . codecov
    - pip install nbformat[test]
script:
    - py.test -v --cov nbformat nbformat
after_success:
    - codecov
matrix:
  allow_failures:
    - python: "nightly"

